import {
  AlertCircle,
  BookOpen,
  Braces,
  CheckCircle2,
  Code2,
  Download,
  Eye,
  FileJson,
  FileText,
  Filter,
  Gauge,
  Globe,
  HelpCircle,
  KeyRound,
  Layers,
  Lock,
  Megaphone,
  Network,
  Rocket,
  Route,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Tag,
  Terminal,
  UserCheck,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  alert: AlertCircle,
  book: BookOpen,
  braces: Braces,
  check: CheckCircle2,
  code: Code2,
  download: Download,
  eye: Eye,
  file: FileJson,
  filter: Filter,
  gauge: Gauge,
  globe: Globe,
  help: HelpCircle,
  key: KeyRound,
  layers: Layers,
  lock: Lock,
  megaphone: Megaphone,
  network: Network,
  rocket: Rocket,
  route: Route,
  server: Server,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  tag: Tag,
  terminal: Terminal,
  user: UserCheck,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function NavIcon({ name, className }: { name?: string | undefined; className?: string }) {
  const Icon = (name && ICONS[name]) || FileText;
  return <Icon className={className} />;
}
