import { z } from "zod";
declare const EnvironmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    APP_URL: z.ZodDefault<z.ZodString>;
    INGESTION_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_URL: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_USER: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_PASSWORD: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_DB: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    NEXTAUTH_SECRET: z.ZodDefault<z.ZodString>;
    NEXTAUTH_URL: z.ZodDefault<z.ZodString>;
    INGESTION_PORT: z.ZodDefault<z.ZodNumber>;
    INGESTION_RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    INGESTION_RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodNumber>;
    MAX_EVENT_PAYLOAD_BYTES: z.ZodDefault<z.ZodNumber>;
    EVENT_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    EVENT_FLUSH_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    KAFKA_BROKERS: z.ZodDefault<z.ZodString>;
    KAFKA_TOPIC: z.ZodDefault<z.ZodString>;
    KAFKA_DLQ_TOPIC: z.ZodDefault<z.ZodString>;
    KAFKA_CONSUMER_GROUP: z.ZodDefault<z.ZodString>;
    /** @deprecated Use KAFKA_TOPIC. Kept so old .env files still parse. */
    QUEUE_NAME: z.ZodDefault<z.ZodString>;
    DERIVE_GEO_AT_EDGE: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    STORE_RAW_IP: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    DEFAULT_RETENTION_MONTHS: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    APP_URL: string;
    INGESTION_URL: string;
    DATABASE_URL: string;
    CLICKHOUSE_URL: string;
    CLICKHOUSE_USER: string;
    CLICKHOUSE_PASSWORD: string;
    CLICKHOUSE_DB: string;
    REDIS_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    INGESTION_PORT: number;
    INGESTION_RATE_LIMIT_MAX: number;
    INGESTION_RATE_LIMIT_WINDOW_MS: number;
    MAX_EVENT_PAYLOAD_BYTES: number;
    EVENT_BATCH_SIZE: number;
    EVENT_FLUSH_INTERVAL_MS: number;
    KAFKA_BROKERS: string;
    KAFKA_TOPIC: string;
    KAFKA_DLQ_TOPIC: string;
    KAFKA_CONSUMER_GROUP: string;
    QUEUE_NAME: string;
    DERIVE_GEO_AT_EDGE: boolean;
    STORE_RAW_IP: boolean;
    DEFAULT_RETENTION_MONTHS: number;
}, {
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    APP_URL?: string | undefined;
    INGESTION_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    CLICKHOUSE_URL?: string | undefined;
    CLICKHOUSE_USER?: string | undefined;
    CLICKHOUSE_PASSWORD?: string | undefined;
    CLICKHOUSE_DB?: string | undefined;
    REDIS_URL?: string | undefined;
    NEXTAUTH_SECRET?: string | undefined;
    NEXTAUTH_URL?: string | undefined;
    INGESTION_PORT?: number | undefined;
    INGESTION_RATE_LIMIT_MAX?: number | undefined;
    INGESTION_RATE_LIMIT_WINDOW_MS?: number | undefined;
    MAX_EVENT_PAYLOAD_BYTES?: number | undefined;
    EVENT_BATCH_SIZE?: number | undefined;
    EVENT_FLUSH_INTERVAL_MS?: number | undefined;
    KAFKA_BROKERS?: string | undefined;
    KAFKA_TOPIC?: string | undefined;
    KAFKA_DLQ_TOPIC?: string | undefined;
    KAFKA_CONSUMER_GROUP?: string | undefined;
    QUEUE_NAME?: string | undefined;
    DERIVE_GEO_AT_EDGE?: string | undefined;
    STORE_RAW_IP?: string | undefined;
    DEFAULT_RETENTION_MONTHS?: number | undefined;
}>;
export type Environment = z.infer<typeof EnvironmentSchema>;
export declare const env: {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    APP_URL: string;
    INGESTION_URL: string;
    DATABASE_URL: string;
    CLICKHOUSE_URL: string;
    CLICKHOUSE_USER: string;
    CLICKHOUSE_PASSWORD: string;
    CLICKHOUSE_DB: string;
    REDIS_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    INGESTION_PORT: number;
    INGESTION_RATE_LIMIT_MAX: number;
    INGESTION_RATE_LIMIT_WINDOW_MS: number;
    MAX_EVENT_PAYLOAD_BYTES: number;
    EVENT_BATCH_SIZE: number;
    EVENT_FLUSH_INTERVAL_MS: number;
    KAFKA_BROKERS: string;
    KAFKA_TOPIC: string;
    KAFKA_DLQ_TOPIC: string;
    KAFKA_CONSUMER_GROUP: string;
    QUEUE_NAME: string;
    DERIVE_GEO_AT_EDGE: boolean;
    STORE_RAW_IP: boolean;
    DEFAULT_RETENTION_MONTHS: number;
};
export {};
//# sourceMappingURL=index.d.ts.map